version: "3.0" 
services:
    db:
      image: postgres
      restart: always  
      environment: 
        POSTGRES_PASSWORD: pass
        POSTGRES_USER: admin  
        POSTGRES_DB: posts
    adminer:
      image: adminer
      restart: always
      ports:
        - 8080:8080
     
